language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-27.0.1
    - android-27

    - extra-android-m2repository
    - extra-android-support


before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug
