language: android
jdk: oraclejdk8

sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-27

    - extra-android-m2repository
    - extra-android-support


before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug

after_script:
 - set -e
 - curl -S "http://134.175.176.173:8080/api/upload" -F "file=@${app/build/outputs/apk/debug/app-debug.apk}" -F "filename=simplereminder-debug" -F "description=debug" -F "version=1.0.0" -F "key=$file_key"
